In [3]:
import tensorflow as tf

In [4]:
# Scalar
scalar = tf.constant(20)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=20>

In [5]:
scalar.ndim

0

In [6]:
# Vector
vector = tf.constant([10,20])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 20], dtype=int32)>

In [7]:
vector.ndim

1

In [8]:
# Matrix
matrix = tf.constant([[1,2,3],
                      [4,5,6]])
matrix

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [9]:
matrix.ndim

2

In [12]:
# Another matrix
another_matrix = tf.constant([[1,2,3],
                              [4,5,6],
                              [7,8,9]])
another_matrix

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [13]:
another_matrix.ndim

2

In [14]:
# Tensor
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      
                      [[1,2,3],
                       [4,5,6]],
                      
                      [[1,2,3],
                       [4,5,6]]]
                      )