In [1]:
import tensorflow as tf

In [2]:
# Scalar
scalar = tf.constant(20)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=20>

In [3]:
scalar.ndim

0

In [4]:
# Vector
vector = tf.constant([10,20])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 20], dtype=int32)>

In [5]:
vector.ndim

1

In [6]:
# Matrix
matrix = tf.constant([[1,2,3],
                      [4,5,6]])
matrix

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
# Another matrix
another_matrix = tf.constant([[1,2,3],
                              [4,5,6],
                              [7,8,9]])
another_matrix

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [9]:
another_matrix.ndim

2

In [10]:
# Tensor
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      
                      [[1,2,3],
                       [4,5,6]],
                      
                      [[1,2,3],
                       [4,5,6]]]
                      )
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]], dtype=int32)>

In [11]:
tensor.ndim

3

In [12]:
# Variable
variable = tf.Variable(20)
variable

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=20>

In [13]:
variable.assign(10)
variable

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=10>

In [14]:
rand_tensors1 = tf.random.Generator.from_seed(7)
rand_tensors1 = rand_tensors1.normal(shape=(3,2))

rand_tensors2 = tf.random.Generator.from_seed(7)
rand_tensors2 = rand_tensors2.normal(shape=(3,2))

In [15]:
rand_tensors1, rand_tensors2, rand_tensors1 == rand_tensors2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [16]:
# Shuffle the tensor

non_shuffled = tf.constant([[1,2,3],
                            [4,5,6],
                            [7,8,9]])
non_shuffled

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [17]:
# Operational Seed
shuffle = tf.random.shuffle(non_shuffled, seed=42)
shuffle

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]], dtype=int32)>

In [18]:
# Global Seed
tf.random.set_seed(42)
shuffle = tf.random.shuffle(non_shuffled)
shuffle

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]], dtype=int32)>

In [19]:
import numpy as np
numpy_A = np.arange(1,25)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [20]:
A = tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int64, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])>

In [21]:
A = tf.constant(numpy_A,shape=(3,8))
A

<tf.Tensor: shape=(3, 8), dtype=int64, numpy=
array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]])>

In [22]:
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [23]:
# Attributes of Tensor
print("Datatype:",rank_4_tensor.dtype)
print("Number of dimensions:",rank_4_tensor.ndim)
print("Shape of Tensor:", rank_4_tensor.shape)
print("Elemnets along the 0 axis:",rank_4_tensor.shape[1])
print("Elemnets along the 0 axis:",rank_4_tensor.shape[-1])
print("Total number of elements in our tensor:", tf.size(rank_4_tensor))
print("Total number of elements in our tensor:", tf.size(rank_4_tensor).numpy())


Datatype: <dtype: 'float32'>
Number of dimensions: 4
Shape of Tensor: (2, 3, 4, 5)
Elemnets along the 0 axis: 3
Elemnets along the 0 axis: 5
Total number of elements in our tensor: tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor: 120


In [24]:
# Indexing tensors
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [25]:
# Get the first element from each dimension from index except for the final one
rank_4_tensor[:-1,:,:,:1]

<tf.Tensor: shape=(1, 3, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [26]:
# Create a rank 2 tensors (2 dimensions)
rank_2_tensors = tf.zeros(shape=[2,4])
rank_2_tensors.ndim

2

In [27]:
rank_2_tensors = tf.constant([[3,4],
                              [5,6]])
rank_2_tensors

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6]], dtype=int32)>

In [28]:
# Last item of each rank of tensor
rank_2_tensors[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 6], dtype=int32)>

In [29]:
rank_3_tensors = rank_2_tensors[..., tf.newaxis]
rank_3_tensors

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[3],
        [4]],

       [[5],
        [6]]], dtype=int32)>

In [35]:
rank_3_tensors = tf.expand_dims(rank_2_tensors,axis=-1)
rank_3_tensors.shape
rank_3_tensors

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[3],
        [4]],

       [[5],
        [6]]], dtype=int32)>

In [36]:
rank_3_tensors = tf.expand_dims(rank_2_tensors,axis=1)
rank_3_tensors.shape
rank_3_tensors

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[3, 4]],

       [[5, 6]]], dtype=int32)>

In [38]:
rank_3_tensors = tf.expand_dims(rank_2_tensors,axis=0)
rank_3_tensors.shape
rank_3_tensors

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[3, 4],
        [5, 6]]], dtype=int32)>

In [42]:
# Manipulating tensors
rank_2_tensors
rank_2_tensors * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[30, 40],
       [50, 60]], dtype=int32)>

In [47]:
tf.multiply(rank_2_tensors,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[30, 40],
       [50, 60]], dtype=int32)>

In [46]:
tf.math.multiply(rank_2_tensors,rank_2_tensors)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 9, 16],
       [25, 36]], dtype=int32)>

In [49]:
# Matrix Multiplication
tf.matmul(rank_2_tensors,rank_2_tensors)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[29, 36],
       [45, 56]], dtype=int32)>

In [50]:
rank_2_tensors @ rank_2_tensors

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[29, 36],
       [45, 56]], dtype=int32)>

In [51]:
rank_2_tensors * rank_2_tensors

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 9, 16],
       [25, 36]], dtype=int32)>

In [57]:
x = tf.constant([[1,2],
                 [3,4],
                 [5,6]])
x

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [58]:
x

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [59]:
y = tf.reshape(x, shape=(2,3))
y

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [60]:
x @ y


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]], dtype=int32)>

In [63]:
tf.matmul(y,x)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[22, 28],
       [49, 64]], dtype=int32)>

In [64]:
x

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [66]:
tf.transpose(x)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]], dtype=int32)>

In [69]:
tf.reshape(x, shape= (2,3))


<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [70]:
x @ y

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]], dtype=int32)>

In [71]:
tf.matmul(x,y)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]], dtype=int32)>

In [80]:
tf.tensordot(x,y, axes=1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]], dtype=int32)>

In [84]:
# Change the datatype of error
tf.cast(x, dtype=tf.int16)

<tf.Tensor: shape=(3, 2), dtype=int16, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int16)>

In [85]:
# Aggregating tensors
D = tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [88]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [89]:
e = tf.constant(np.random.randint(0,100,size=50))

In [90]:
e

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([16, 27, 31,  4, 51,  5, 90, 19, 58, 26, 10, 41, 86, 36, 85, 20, 66,
       61, 13, 12, 81, 13, 49, 65, 51, 97, 15, 58, 65,  6, 87, 20, 90,  1,
       53, 58, 14, 24, 95, 40, 97, 98, 25, 83, 41, 81, 13, 60, 38, 14])>

In [93]:
tf.reduce_min(e)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [98]:
# variance
tf.math.reduce_variance(tf.cast(e,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=916.4116>

In [104]:
# Find the positional minimum and maximum
tf.random.set_seed(42)
g = tf.random.uniform(shape=[50])
g

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [108]:
tf.argmax(g)
g[42]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [111]:
g[tf.argmin(g)] == tf.reduce_min(g)

<tf.Tensor: shape=(), dtype=bool, numpy=True>