In [1]:
import tensorflow as tf

In [2]:
# Scalar
scalar = tf.constant(20)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=20>

In [3]:
scalar.ndim

0

In [4]:
# Vector
vector = tf.constant([10,20])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 20], dtype=int32)>

In [5]:
vector.ndim

1

In [6]:
# Matrix
matrix = tf.constant([[1,2,3],
                      [4,5,6]])
matrix

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
# Another matrix
another_matrix = tf.constant([[1,2,3],
                              [4,5,6],
                              [7,8,9]])
another_matrix

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [9]:
another_matrix.ndim

2

In [10]:
# Tensor
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      
                      [[1,2,3],
                       [4,5,6]],
                      
                      [[1,2,3],
                       [4,5,6]]]
                      )
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]], dtype=int32)>

In [11]:
tensor.ndim

3

In [12]:
# Variable
variable = tf.Variable(20)
variable

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=20>

In [13]:
variable.assign(10)
variable

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=10>

In [15]:
rand_tensors1 = tf.random.Generator.from_seed(7)
rand_tensors1 = rand_tensors1.normal(shape=(3,2))

rand_tensors2 = tf.random.Generator.from_seed(7)
rand_tensors2 = rand_tensors2.normal(shape=(3,2))

In [16]:
rand_tensors1, rand_tensors2, rand_tensors1 == rand_tensors2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [18]:
# Shuffle the tensor
non_shuffled = tf.constant([[1,2,3],
                            [4,5,6],
                            [7,8,9]])
non_shuffled

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [39]:
# Operational Seed
shuffle = tf.random.shuffle(non_shuffled, seed=42)
shuffle

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[7, 8, 9],
       [1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [54]:
# Global Seed
tf.random.set_seed(42)
shuffle = tf.random.shuffle(non_shuffled)
shuffle

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]], dtype=int32)>